# Generated by Django 4.2.4 on 2023-09-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
