# Generated by Django 4.2.4 on 2023-08-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_status',
            new_name='status',
        ),
    ]
