name: Django Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker-Compose
        run: docker-compose up -d
      - name: PostgreSQL Check
        run: |
          timeout 90s bash -c 'until docker-compose exec -T db pg_isready; do sleep 5; done'
        run: docker-compose run backend sh -c "flake8 && pytest ."

# what is wrong